name: Builds on Windows

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check out, and set up the node infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      # Get local dependencies
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn build
