name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      # Get local dependencies
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn build

      # PR: Deploy if we can
      - name: Deploy PR Version
        if: github.event_name == 'pull_request'
        run: 'if test -z "$NOW_ACCESS_TOKEN"; then echo "Skipping deploy";
          else cp -r packages/typescriptlang-org/public packages/typescriptlang-org/typescript-v2-$PR_NUMBER ; npx now packages/typescriptlang-org/typescript-v2-$PR_NUMBER --token="$NOW_ACCESS_TOKEN"  --confirm; fi'
        env:
          NOW_ACCESS_TOKEN: ${{ secrets.NOW_ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      # Run any tests
      - run: yarn workspaces run test --ci
        env:
          CI: true

  lighthouse_danger:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install

      - run: yarn workspace typescriptlang-org run create-lighthouse-json
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Run Lighthouse and test budgets
        uses: orta/lighthouse-ci-action@ort-fork-pr-29
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

      # danger for PR builds
      - if: github.event_name == 'pull_request'
        run: 'if test -z "$GITHUB_TOKEN"; then echo "Skipping danger"; else yarn danger ci; fi'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
