name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      # Cache yarn deps, to speed up CI
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Get dependencies for building the ebooks
      - run: sudo apt-get update
      - run: sudo apt install calibre

      # Install, should be absically instant if cached
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Verify dependencies are hooked up right
      - run: node test/verifyPackageVersions.js

      # Build the packages
      - run: yarn bootstrap
      - run: yarn workspace typescriptlang-org build

      #  Blocked on https://github.com/Azure/static-web-apps/issues/147
      #

      # PR deploys via static web apps
      # - name: "Make a fake 'app' for the azure project of the static HTML"
      #   run: |
      #     mkdir fakeapp
      #     mv packages/typescriptlang-org/public fakeapp/public
      #     ls fakeapp
      #     ls fakeapp/public
      #     echo '{ "name": "fake", "scripts": { "build": "" } }' > fakeapp/package.json

      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v0.0.1-preview
      #   if: github.event.base.repo.id == github.event.head.repo.id
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MEADOW_0C9756810 }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     action: "upload"
      #     app_location: "fakeapp"
      #     api_location: "api"
      #     app_artifact_location: "public"

      # Verify it compiles
      - run: yarn compile
      # Run all the package's tests
      - run: yarn test
        env:
          CI: true

      - name: "Validates that TypeScript plugins work"
        run: npm init typescript-playground-plugin playground-my-plugin

      # danger for PR builds
      - if: github.event_name == 'pull_request' && github.event.base.repo.id == github.event.head.repo.id
        run: "yarn danger ci"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_DEPLOY_URL_ROOT: ${{ steps.deploy.outputs.static_web_app_url }}
  #
  #  Blocked on https://github.com/Azure/static-web-apps/issues/147
  #
  # close_pull_request_job:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.base.repo.id == github.event.head.repo.id
  #   runs-on: ubuntu-latest
  #   name: Close Pull Request Job
  #   steps:
  #     - name: Close Pull Request
  #       id: closepullrequest
  #       uses: Azure/static-web-apps-deploy@v0.0.1-preview
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MEADOW_0C9756810 }}
  #         action: "close"
