name: Build Website For Production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out, and set up the node/ruby infra
    - uses: actions/checkout@v1
      with:
       submodules: "true"
    - uses: actions/setup-node@v1
    - uses: actions/setup-ruby@v1

    # Get local dependencies
    - run: yarn install
    # danger for PR builds
    - if: github.event_name == 'pull_request'
      run: yarn danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: (cd src/play && yarn install && yarn setup)
    - run: gem install bundler -v 1.16.1
    - run: bundle install

    # Build v1
    - name: Build website v1
      run: gulp publish

    # Switch to node 13
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    # For epub -> PDF generation
    - run: sudo apt install calibre

    # CI: Deploy to the right branch
    - name: Deploy + Publish
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: 'SITE-PRODUCTION'
        PUBLISH_DIR: ./site
