name: Deploy Staging on Push

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - uses: actions/setup-ruby@v1

    - run: git submodule init
    - run: git submodule update
    
    - run: gulp publish
    - run: gulp deploy
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
