name: Build Website To Staging

on:
  push:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      # Build v2
      - name: Build website v2
        run: |
          yarn install
          yarn bootstrap
          yarn build
          yarn build-site
          cp -r packages/typescriptlang-org/public site

    # CI: Deploy to the right branch
    - name: Deploy + Publish
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: 'SITE-STAGING'
        PUBLISH_DIR: ./site
