name: Daily updates for v2

# For testing
# on: push

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install

      # Update all the translation issues on a nightly basis
      - run: node packages/typescriptlang-org/scripts/updateGitHubTranslationIssues.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}

      # Setup Git
      - run: git config user.name "typescript-bot"
      - run: git config user.email "bot@typescriptlang.org"
      - run: git checkout master

      - run: git remote add authorigin 'https://$GITHUB_TOKEN@github.com/microsoft/TypeScript-website.git' > /dev/null 2>&1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}

      - run: git commit --allow-empty -m "Nightly Deploy"
      - run: git push authorigin master:release -f
