name: Daily updates for v2

# For testing
# on: push

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Update all the translation issues on a nightly basis
      - run: node packages/typescriptlang-org/scripts/updateGitHubTranslationIssues.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
